name: push-website

on:
  push:
    # 当master分支提交代码时触发
    branches: [ master ]

# 具体执行的任务
jobs:
  build:
    runs-on: Windows Server 2008
    steps:
      - uses: action/checkout@v2
      - name: install nodejs
        uses: actions/setup-node@v3.5.1
        with: 
          node-version: "14.X"
      - name: install deps
        run: npm install
      - name: build app
        run: npm run build
      - name: copy dist file with scp
        uses: appleboy/scp-action@v0.0.1
        with:
          host: ${{secrets.REMOTE_HOST}}
          username: ${{secrets.REMOTE_USERNAME}}
          password: ${{secrets.REMOTE_PWD}}
          port: 7288
          source: 'dist/'
          target: ${{secrets.REMOTE_TARGET}}
